export const colors = {
    inherit: { value: 'inherit', hasRange: false, hasOpacity: false },
    current: { value: 'currentColor', hasRange: false, hasOpacity: false },
    transparent: { value: 'transparent', hasRange: false, hasOpacity: false },
    black: { value: '#000000', hasRange: false, hasOpacity: true },
    white: { value: '#ffffff', hasRange: false, hasOpacity: true },
    slate: { value: '#f8fafc', hasRange: true, hasOpacity: true },
    gray: { value: '#f9fafb', hasRange: true, hasOpacity: true },
    zinc: { value: '#fafafa', hasRange: true, hasOpacity: true },
    neutral: { value: '#fafafa', hasRange: true, hasOpacity: true },
    stone: { value: '#fafaf9', hasRange: true, hasOpacity: true },
    red: { value: '#fef2f2', hasRange: true, hasOpacity: true },
    orange: { value: '#fff7ed', hasRange: true, hasOpacity: true },
    amber: { value: '#fffbeb', hasRange: true, hasOpacity: true },
    yellow: { value: '#fefce8', hasRange: true, hasOpacity: true },
    lime: { value: '#f7fee7', hasRange: true, hasOpacity: true },
    green: { value: '#f0fdf4', hasRange: true, hasOpacity: true },
    emerald: { value: '#ecfdf5', hasRange: true, hasOpacity: true },
    teal: { value: '#f0fdfa', hasRange: true, hasOpacity: true },
    cyan: { value: '#ecfeff', hasRange: true, hasOpacity: true },
    sky: { value: '#f0f9ff', hasRange: true, hasOpacity: true },
    blue: { value: '#eff6ff', hasRange: true, hasOpacity: true },
    indigo: { value: '#eef2ff', hasRange: true, hasOpacity: true },
    violet: { value: '#f5f3ff', hasRange: true, hasOpacity: true },
    purple: { value: '#fae8ff', hasRange: true, hasOpacity: true },
    fuchsia: { value: '#fdf4ff', hasRange: true, hasOpacity: true },
    pink: { value: '#fdf2f8', hasRange: true, hasOpacity: true },
    rose: { value: '#fff1f2', hasRange: true, hasOpacity: true },
};

export const colorRange = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

export const opacities = {
    '0': '0',
    '5': '0.05',
    '10': '0.1',
    '15': '0.15',
    '20': '0.2',
    '25': '0.25',
    '30': '0.3',
    '35': '0.35',
    '40': '0.4',
    '45': '0.45',
    '50': '0.5',
    '55': '0.55',
    '60': '0.6',
    '65': '0.65',
    '70': '0.7',
    '75': '0.75',
    '80': '0.8',
    '85': '0.85',
    '90': '0.9',
    '95': '0.95',
    '100': '1'
};
