// Pseudo-class tanımları
export const pseudoClasses = {
    'hover': () => [':hover'],
    'focus-visible': () => [':focus-visible'],
    'focus-within': () => [':focus-within'],
    'focus': () => [':focus'],
    'active': () => [':active'],
    'visited': () => [':visited'],
    'link': () => [':link'],
    'checked': () => [':checked'],
    'disabled': () => [':disabled'],
    'enabled': () => [':enabled'],
    'required': () => [':required'],
    'optional': () => [':optional'],
    'read-only': () => [':read-only'],
    'read-write': () => [':read-write'],
    'placeholder-shown': () => [':placeholder-shown'],
    'target': () => [':target'],
    'nth-child': () => [':nth-child'],
    'nth-last-child': () => [':nth-last-child'],
    'first-of-type': () => [':first-of-type'],
    'last-of-type': () => [':last-of-type'],
    'nth-of-type': () => [':nth-of-type'],
    'nth-last-of-type': () => [':nth-last-of-type'],
    'only-child': () => [':only-child'],
    'only-of-type': () => [':only-of-type'],
    'empty': () => [':empty'],
    'odd': () => [':nth-child(odd)'],
    'even': () => [':nth-child(even)'],
    'autofill': () => [':autofill'],
    'invalid': () => [':invalid'],
    'valid': () => [':valid'],
    'indeterminate': () => [':indeterminate'],
    'out-of-range': () => [':out-of-range'],
    'in-range': () => [':in-range'],
    'first': () => [':first-child'],
    'last': () => [':last-child'],
};

// Pseudo-element tanımları
export const pseudoElements = {
    'before': () => ['::before'],
    'after': () => ['::after'],
    'first-letter': () => ['::first-letter'],
    'first-line': () => ['::first-line'],
    'selection': () => ['::selection'],
    'placeholder': () => ['::placeholder'],
    'backdrop': () => ['::backdrop'],
    'marker': () => ['::marker', ' *::marker'],
    'file-selector-button': () => ['::file-selector-button'],
};
