name: Eglador CSS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Repository'yi Klonla
        uses: actions/checkout@v3

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Bağımlılıkları Kur
        run: npm install

      - name: Config Dosyasını Oluştur
        run: npm run init

      - name: Build Komutunu Çalıştır
        run: npm run build

      - name: Watch Komutunu Test Et
        run: npm run watch
